/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/persons/{ssn}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get person by SSN
         * @description Retrieves a single person's details based on their SSN.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description SSN of the person to retrieve */
                    ssn: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Person details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Person"];
                    };
                };
                /** @description Person not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Person: {
            /**
             * Format: int64
             * @example 1
             */
            id: number;
            /** @example John */
            firstName: string;
            /** @example Doe */
            lastName: string;
            /** @example 111-222-3333 */
            ssn: string;
        };
        Error: {
            /** Format: int32 */
            code: number;
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
