openapi: 3.0.0
info:
  title: Persons API
  version: 1.0.0
  description: A simple API to get person details by SSN.
paths:
  /persons/{ssn}:
    get:
      summary: Get person by SSN
      description: Retrieves a single person's details based on their SSN.
      parameters:
        - name: ssn
          in: path
          required: true
          description: SSN of the person to retrieve
          schema:
            type: string
            pattern: '^\d{3}-\d{3}-\d{4}$'
            example: '111-222-3333'
      responses:
        '200':
          description: Person details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '404':
          description: Person not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Person:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        firstName:
          type: string
          example: 'John'
        lastName:
          type: string
          example: 'Doe'
        ssn:
          type: string
          pattern: '^\d{3}-\d{3}-\d{4}$'
          example: '111-222-3333'
      required:
        - id
        - firstName
        - lastName
        - ssn
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message
